## Приклад 1


In [1]:
import numpy as np

Вхідні дані

In [2]:
# Промисловість
industry1 = 820 #x11
industry2 = 450 #x12

demand_industry = 970 #y1

# повний випуск x1
release_industry = industry1 + industry2 + demand_industry

# Сільське господарство
agriculture1 = 350 #x21
agriculture2 = 400 #x22

demand_agriculture = 750 #y2

# повний випуск x2
release_agriculture = agriculture1 + agriculture2 + demand_agriculture

In [3]:
# прогноз випуску
predicted_industry = 1150
predicted_agriculture = 700

In [4]:
# Знаходимо технологічну матрицю
A = np.array([[industry1 / release_industry, industry2 / release_agriculture],
              [agriculture1 / release_industry, agriculture2 / release_agriculture]])

A

array([[0.36607143, 0.3       ],
       [0.15625   , 0.26666667]])

Вектор прогнозованого попиту


In [5]:
c = np.array([[predicted_industry], [predicted_agriculture]])
c

array([[1150],
       [ 700]])

Одинична матриця 2х2

In [6]:
E = np.eye(2)
E

array([[1., 0.],
       [0., 1.]])

Розрахуємо матрицю повних витрат

In [7]:
B = np.linalg.inv(np.subtract(E, A))
B

array([[1.75436098, 0.71769313],
       [0.3737985 , 1.51655393]])

In [8]:
x = np.dot(B, c)
print(f"Результуюча матриця вийшла: \n({x[0]})\n({x[1]})")

Результуюча матриця вийшла: 
([2519.9003204])
([1491.45603418])


## Приклад 2

In [9]:
A = np.array([[0.1, 0.5, 0.1], [0.3, 0.2, 0.1], [0.3, 0.1, 0.4]])
A

array([[0.1, 0.5, 0.1],
       [0.3, 0.2, 0.1],
       [0.3, 0.1, 0.4]])

обчислення власних чисел за допомогою сторонніх бібліотек

In [10]:
eig_val, eig_vec = np.linalg.eig(A)
eig_val

array([-0.23748703,  0.68572156,  0.25176547])

обчислення власних чисел вручну без бібліотек

In [11]:
from sympy import symbols, solve, Matrix

# Define the symbol for lambda
lambda_symbol = symbols('λ')

# Define the matrix A - λI
A_lambda_I = np.array([
    [0.1 - lambda_symbol, 0.5, 0.1],
    [0.3, 0.2 - lambda_symbol, 0.1],
    [0.3, 0.1, 0.4 - lambda_symbol]
])

# Calculate the determinant of A - λI
determinant = (
    (A_lambda_I[0,0] * ((A_lambda_I[1,1] * A_lambda_I[2,2]) - (A_lambda_I[1,2] * A_lambda_I[2,1]))) -
    (A_lambda_I[0,1] * ((A_lambda_I[1,0] * A_lambda_I[2,2]) - (A_lambda_I[1,2] * A_lambda_I[2,0]))) +
    (A_lambda_I[0,2] * ((A_lambda_I[1,0] * A_lambda_I[2,1]) - (A_lambda_I[1,1] * A_lambda_I[2,0])))
)

# Solve the characteristic equation det(A - λI) = 0 for λ
eigenvalue_solutions = solve(determinant, lambda_symbol)
eigenvalue_solutions

[-0.237487028183629 + 0.e-23*I,
 0.251765465158031 + 0.e-23*I,
 0.685721563025597 - 0.e-23*I]

Обрахування характеристичного поліному за допомогою сторонніх бібліотек:

In [12]:
# Define the symbol for lambda
lambda_symbol = symbols('λ')

# Define the matrix A
A_matrix = Matrix([
    [0.1, 0.5, 0.1],
    [0.3, 0.2, 0.1],
    [0.3, 0.1, 0.4]
])

# Get the characteristic polynomial of matrix A
char_poly = A_matrix.charpoly(lambda_symbol)

# Get the coefficients of the characteristic polynomial
char_poly_coeffs = char_poly.all_coeffs()
char_poly_coeffs
print(f"Характеристичний поліном: {char_poly}, \nкоефіцієнти: {char_poly_coeffs}")

Характеристичний поліном: PurePoly(1.0*λ**3 - 0.7*λ**2 - 0.05*λ + 0.041, λ, domain='RR'), 
коефіцієнти: [1.00000000000000, -0.700000000000000, -0.0500000000000000, 0.0410000000000000]


Обрахування характеристичного поліному вручну, без бібліотек:

In [13]:
# Function to calculate the trace of the matrix (sum of diagonal elements)
def trace(matrix):
    return sum(matrix[i][i] for i in range(len(matrix)))

# Function to calculate the determinant of a 3x3 matrix
def determinant_3x3(matrix):
    return (
        matrix[0][0] * (matrix[1][1] * matrix[2][2] - matrix[1][2] * matrix[2][1]) -
        matrix[0][1] * (matrix[1][0] * matrix[2][2] - matrix[1][2] * matrix[2][0]) +
        matrix[0][2] * (matrix[1][0] * matrix[2][1] - matrix[1][1] * matrix[2][0])
    )

# Calculate the trace (a_2)
a_2 = trace(A)

# Calculate the determinant (a_0)
a_0 = determinant_3x3(A)

# Calculate the coefficient a_1, we subtract the sum of the products of pairs of the matrix's off-diagonal entries
# in each 2x2 principal minor from the sum of the products of pairs of the matrix's diagonal entries.
a_1 = (
    (A[0][0]*A[1][1] + A[0][0]*A[2][2] + A[1][1]*A[2][2]) - 
    (A[0][1]*A[1][0] + A[0][2]*A[2][0] + A[1][2]*A[2][1])
)

# Since the leading coefficient is 1, the characteristic polynomial can be represented as:
# λ^3 - a_2*λ^2 + a_1*λ - a_0 = 0
# We return the coefficients in descending order of λ powers
(1, -a_2, a_1, -a_0)

(1, -0.7000000000000001, -0.04999999999999999, 0.041)

число Фробеніуса-найбільше власне значення по модулю, тобто:

In [14]:
Frobenius_num = max(abs(eig_val))
Frobenius_num

0.6857215630255973

Щодо продуктивності матриці, що матриця А є продуктивною бо число Фробеніуса < 1


Правий та лівий вектори

In [20]:
import scipy
eig_values, eig_left_vectors, eig_vectors = scipy.linalg.eig(A, right = True, left = True)
index = 1
print("Власні числа матриці A")
print(f"{eig_values}")


Власні числа матриці A
[-0.23748703+0.j  0.68572156+0.j  0.25176547+0.j]


In [23]:
# eigenvalues, _ = np.linalg.eig(A)

def complexto_real(x):
    if x.imag == 0:
        return x.real
    else:
        return x

def complexto_real_vector(vector):
    if (vector[0] < 0):
        vector = vector * (-1)
    isReal = True
    for val in vector:
        if val.imag != 0:
            isReal = False
            break
    if isReal:
        return vector.real
    else:
        return vector

# print("Число Фробеніуса:")
frobenius_value = max(eig_values, key = lambda x: abs(x))
frobenius_value = complexto_real(frobenius_value)
# print(f"{frobenius_value}")

right_frobenius_vector = eig_vectors[:, eig_values == frobenius_value]
right_frobenius_vector = complexto_real_vector(right_frobenius_vector)
print(f"Правий вектор Фробеніуса{right_frobenius_vector}")

_, eig_left_vectors = np.linalg.eig(A.T)
left_frobenius_vector = eig_left_vectors[:, eig_values == frobenius_value]
left_frobenius_vector = complexto_real_vector(left_frobenius_vector)
print(f"Лівий вектор Фробеніуса {left_frobenius_vector}")

Правий вектор Фробеніуса[[0.52205684]
 [0.46909495]
 [0.71232477]]
Лівий вектор Фробеніуса [[0.57785145]
 [0.68589885]
 [0.44230134]]


##### Матриця повних витрат

Матриця повних витрат B для деякої матриці A розраховується як сума ряду:

B = E + A + A**2 + ...

Цей ряд збігається, якщо спектральний радіус матриці A менший за 1, що гарантує, що ефекти від додаткових "поколінь" витрат (потужностей A) стають все меншими і врешті решт прямують до нуля.

Математично, якщо ряд сходиться, то матриця повних витрат B може бути виражена як:

B = (E - A) ^ -1


Дослідимо на збіжність дану послідовність

In [74]:
from numpy.linalg import matrix_power 

# Визначаємо поріг збіжності для елементів матриці
convergence_threshold = 0.01

# Ініціалізуємо початкову суму з одиничною матрицею того ж розміру, що й A
current_sum = np.eye(A.shape[0])
iteration = 0
max_iterations = 1000000
converged = False

while (not converged or iteration >= max_iterations):
    # Обчислюємо наступну ступінь матриці A (A^n)
    next_power = matrix_power(A, iteration + 1)
    
    # Додаємо ступінь матриці до поточної суми
    new_sum = current_sum + next_power
    iteration += 1

    # Перевіряємо, чи різниця між новою сумою і поточною сумою менше порогу для всіх елементів
    if np.all(np.abs(new_sum - current_sum) < convergence_threshold):
        converged = True
    current_sum = new_sum

# Виводимо результат
current_sum, iteration, converged

(array([[1.60406508, 1.0521698 , 0.43827352],
        [0.71171584, 1.74078624, 0.4047677 ],
        [0.91275075, 0.80683752, 1.94721692]]),
 11,
 True)

Внаслідок наближення маємо матрицю повних витрат В


Вектор цін, якщо вектор доданої вартості буде (0.3 0.4 0.5) буде мати вигляд

p = sB

In [76]:
new_vec = np.array([0.3, 0.4, 0.5])
p = np.dot(new_vec, current_sum)
p

array([1.22228123, 1.41538419, 1.2669976 ])

Отже, маємо вектор цін, враховуючи вектор доданої вартості